-- MySQL Script generated by MySQL Workbench
-- 01/02/17 11:09:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_system_store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_system_store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_system_store` DEFAULT CHARACTER SET utf8 ;
USE `db_system_store` ;

-- -----------------------------------------------------
-- Table `db_system_store`.`CLIENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`CLIENTES` (
  `cli_clientes_id` INT NOT NULL AUTO_INCREMENT,
  `cli_cpf` VARCHAR(45) NULL,
  `cli_cnpj` VARCHAR(45) NULL,
  `cli_nome` VARCHAR(250) NULL,
  `cli_sobrenome` VARCHAR(250) NULL,
  `cli_ativo` VARCHAR(1) NULL,
  `cli_end_enderecos_id` INT NULL,
  PRIMARY KEY (`cli_clientes_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`FORNECEDORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`FORNECEDORES` (
  `for_fornecedores_id` INT NOT NULL AUTO_INCREMENT,
  `for_cpf` VARCHAR(45) NULL,
  `for_cnpj` VARCHAR(45) NULL,
  `for_nome` VARCHAR(250) NULL,
  `for_end_enderecos_id` VARCHAR(45) NULL,
  PRIMARY KEY (`for_fornecedores_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`USUARIOS` (
  `usu_usuarios_id` INT NOT NULL AUTO_INCREMENT,
  `usu_username` VARCHAR(45) NULL,
  `usu_password` VARCHAR(250) NULL,
  `usu_ativo` VARCHAR(1) NULL,
  PRIMARY KEY (`usu_usuarios_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`AUTORIZACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`AUTORIZACAO` (
  `aut_autorizacao_id` INT NOT NULL AUTO_INCREMENT,
  `aut_descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`aut_autorizacao_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`PRODUTOS` (
  `pro_produtos_id` INT NOT NULL AUTO_INCREMENT,
  `pro_referencia` VARCHAR(45) NULL,
  `pro_descricao` VARCHAR(250) NULL,
  `pro_preco` DECIMAL(11,2) NULL,
  `pro_for_fornecedores_id` INT NULL,
  `pro_tpr_tipos_produto_id` INT NULL,
  `pro_data` TIMESTAMP NOT NULL,
  PRIMARY KEY (`pro_produtos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`VENDAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`VENDAS` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`COMPRAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`COMPRAS` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`ESTOQUES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`ESTOQUES` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`MOVIMENTACOES_ESTOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`MOVIMENTACOES_ESTOQUE` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`ORCAMENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`ORCAMENTOS` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`DEVOLUCOES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`DEVOLUCOES` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`PAGAMENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`PAGAMENTOS` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`RECEBIMENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`RECEBIMENTOS` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`NOTAS_FISCAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`NOTAS_FISCAIS` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`METAS_VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`METAS_VENDA` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`TIPOS_PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`TIPOS_PAGAMENTO` (
  `tpg_tipos_pagamento_id` INT NOT NULL AUTO_INCREMENT,
  `tpg_descricao` VARCHAR(250) NULL,
  PRIMARY KEY (`tpg_tipos_pagamento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`TIPOS_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`TIPOS_PRODUTO` (
  `tpr_tipos_produto_id` INT NOT NULL AUTO_INCREMENT,
  `tpr_descricao` VARCHAR(250) NULL,
  PRIMARY KEY (`tpr_tipos_produto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`USUARIOS_AUTORIZACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`USUARIOS_AUTORIZACAO` (
  `uat_usuarios_autorizacao_id` INT NOT NULL AUTO_INCREMENT,
  `uat_usu_usuarios_id` INT NULL,
  `uat_aut_autorizacao_id` INT NULL,
  PRIMARY KEY (`uat_usuarios_autorizacao_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`CORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`CORES` (
  `cor_cores_id` INT NOT NULL AUTO_INCREMENT,
  `cor_descricao` VARCHAR(250) NULL,
  `cor_pro_produtos_id` INT NULL,
  PRIMARY KEY (`cor_cores_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`TAMANHOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`TAMANHOS` (
  `tam_tamanhos_id` INT NOT NULL AUTO_INCREMENT,
  `tam_descricao` VARCHAR(45) NULL,
  `tam_pro_produtos_id` INT NULL,
  PRIMARY KEY (`tam_tamanhos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_system_store`.`ENDERECOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_system_store`.`ENDERECOS` (
  `end_enderecos_id` INT NOT NULL AUTO_INCREMENT,
  `end_logradouro` VARCHAR(250) NULL,
  `end_numero` VARCHAR(45) NULL,
  `end_bairro` VARCHAR(250) NULL,
  `end_cidade` VARCHAR(250) NULL,
  `end_estado` VARCHAR(250) NULL,
  `end_pais` VARCHAR(45) NULL,
  `end_cep` VARCHAR(45) NULL,
  PRIMARY KEY (`end_enderecos_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
